previewsEnabled: false # see https://render.com/docs/preview-environments
previewsExpireAfterDays: 3
services:
- type: web
  name: blockipedia
  env: static
  buildCommand: make build-frontend
  staticPublishPath: ./frontend/public
  pullRequestPreviewsEnabled: true  # see https://render.com/docs/pull-request-previews
  envVars:
  - key: GATSBY_CONTRACT_ADDRESS
    value: test.blockipedia.testnet
  - key: GATSBY_PATH_PREFIX
    value: ""